version: '3.8'

services:
  minecraft:
    container_name: minecraft-server
    image: itzg/minecraft-server
    restart: unless-stopped
    ports: ['25565:25565']
    environment:
      - INIT_MEMORY=1G
      - MAX_MEMORY=8G
      - EULA=true
      - GID=985
    volumes:
      - /home/jack/Games/minecraft-server:/data
  minecraft-overviewer:
    container_name: minecraft-overviewer
    image: mide/minecraft-overviewer:latest
    restart: unless-stopped
    environment:
      - MINECRAFT_VERSION=1.16.4
    volumes:
      - /home/jack/Games/minecraft-server/:/home/minecraft/server/:ro
      - /home/jack/Games/minecraft-overviewer/render/:/home/minecraft/render/:rw
      - /home/jack/Games/minecraft-overviewer/config/config.py:/home/minecraft/config.py
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:2.1.1-alpine
    restart: always
    ports: ['9000:9000']
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - portainer_data:/data

  folding:
    image: yurinnick/folding-at-home
    container_name: folding-at-home
    environment:
      - USER=Anonymous
      - TEAM=225605
      - ENABLE_GPU=false
      - ENABLE_SMP=true
    ports:
      - 7396:7396
      - 36330:36330
    restart: unless-stopped
    command: '--allow 0/0 --web-allow 0/0'

volumes:
  portainer_data:
